# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('image_in', models.ImageField(upload_to='in')),
                ('image_out', models.ImageField(upload_to='out')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_payments', to='client.Car')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_transactions', to='garage.Garage')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='client.Client'),
        ),
    ]
