# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage_manager', '0001_initial'),
        ('client', '0002_auto_20160308_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='parked_in',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars_in_garage', to='garage_manager.GarageManager'),
        ),
    ]
