# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
        ('client', '0003_car_parked_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField(null=True)),
                ('image_in', models.ImageField(null=True, upload_to='in')),
                ('image_out', models.ImageField(null=True, upload_to='out')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_payments', to='client.Car')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_transactions', to='garage.Garage')),
            ],
        ),
    ]
