# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20160324_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-time_in']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='transaction',
            order_with_respect_to=None,
        ),
    ]
