# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='garage.Garage')),
            ],
        ),
    ]
